# 下载 Docker Desktop
# https://docs.docker.com/desktop/install/windows-install/

# 下载 GitHub Actions ACT
# https://github.com/nektos/act/releases

# 运行 GitHub Actions ACT 测试
# act --rebuild --secret-file act_secret_file

name: 自动编译 Python 模块并发布到 PyPI 和 TestPyPI

on: [push]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: 安装安装依赖 pip setuptools wheel twine build
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: 构建 Python 模块
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: 发布到 PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
